#!/bin/bash
for i in *.jpg
do
	echo "$i" "${i%.jpg}.avif"
	/home/liam/magick convert "$i" "${i%.jpg}.avif" &
done

for i in *.png
do
        echo "$i" "${i%.png}.avif"
        /home/liam/magick convert "$i" "${i%.png}.avif" &
done
